# Generated by Django 4.0.6 on 2023-04-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_cart_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=400)),
                ('username', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=200)),
                ('star', models.IntegerField(default=1)),
                ('review', models.TextField()),
            ],
        ),
    ]
